### ISSUE TITLE
Tema - Grupo 4

### ISSUE THREAD

**Issue by wellington36** [fccoelho/Reinforcement-Learning-course#16]
@fccoelho, tivemos um problema com o nosso tema, iamos usar o jogo [galaxypy](https://github.com/wellington36/galaxypy) (de criação propria), mas quando fiz o jogo foi em [kivy](https://github.com/kivy/kivy) em vez de pygame, porém o kivy não aceita muito bem ser controlado por outro código. A gente também pensou em reprogramar o jogo usando pygame mas isso aparentemente não é muito simples assim (e esta saindo um pouco do objetivo).

Então se não tiver problema em trocar o tema, estamos querendo fazer com [campo minado](https://en.wikipedia.org/wiki/Minesweeper_(video_game)) e estamos com alguns avanços diferente do outro jogo.

**Comment by fccoelho** [comment]
Sem problemas @wellington36
